### ISSUE TITLE
Doesnt appeared on archlinux tweak tools

### ISSUE THREAD

**Issue by gaou-piou** [EliverLara/snow#1]
The Snow theme does not appeared on archlinux gnome's tweak tools

**Comment by EliverLara** [comment]
HI, what is your gtk version?, because the theme only works with gtk3.20 +, so if you're using gtk  <  3.20 the theme will not work.

**Comment by klintmane** [comment]
@EliverLara @gaou-piou There is a _typo_ in the project directory structure. The GTK 3 folder should be named `gtk-3.0` instead of `gtk-3.20`. You can manually change it and it will correctly show up on gnome tweak tools.

**Comment by klintmane** [comment]
@EliverLara PR #2 should fix this.

**Comment by EliverLara** [comment]
@klintmane thanks for the observation, you're right, I forgot and I had not realized since I use the terminal directly to changing themes.
