### ISSUE TITLE
Left side of the tab close buttons are cropped

### ISSUE THREAD

**Issue by nnmlss** [EliverLara/snow#11]
I am using elementary OS Juno and left side of all tabs buttons is cropped. I believe it is not a design desigion. The screenshots are from Pantheon Files, Code and Terminal applications. 

![Screenshot from 2019-12-04 21 20 14](https://user-images.githubusercontent.com/1779227/70173718-19d18880-16dc-11ea-9b91-40356e93827d.png)
![Screenshot from 2019-12-04 21 21 30](https://user-images.githubusercontent.com/1779227/70173719-1a6a1f00-16dc-11ea-94b7-6a198eefb46a.png)
![Screenshot from 2019-12-04 21 23 52](https://user-images.githubusercontent.com/1779227/70173853-6917b900-16dc-11ea-943b-ee25c0ecd2ec.png)

**Comment by EliverLara** [comment]
Fixed!
