### ISSUE TITLE
[Snow Alien Branch] bad contrast over Green

### ISSUE THREAD

**Issue by AdsonCicilioti** [EliverLara/snow#12]
Hi @EliverLara ! nice work with this beautiful theme.

In some situations the white text contrast over lime green is very bad. See:
![image](https://user-images.githubusercontent.com/6278398/76684172-6fc1a080-65e8-11ea-8c6c-4ded66903685.png)
on Sidebar panels:
![image](https://user-images.githubusercontent.com/6278398/76684266-3b9aaf80-65e9-11ea-8fd8-3faf8850b336.png)

I have dificulty to read the text.

on your screenshot seems well better:
![image](https://user-images.githubusercontent.com/6278398/76684229-d2b33780-65e8-11ea-8e99-ce902981cb54.png)

On Topbar Shell, the opacity seems are in 0.3. I think on value above 0.75, because on wallpapers more brightest / clear, the white text are unreadable. See:
![image](https://user-images.githubusercontent.com/6278398/76684354-21150600-65ea-11ea-8833-fac3c6897894.png)

Thanks for this nice theme.

**Comment by EliverLara** [comment]
Thanks for the feedback!. Now it looks better.

**Comment by AdsonCicilioti** [comment]
![image](https://user-images.githubusercontent.com/6278398/81373603-7bef4900-90d3-11ea-8a8f-cd2d0c9ef01c.png)

Why this green accent color?
This is ugly.. or not represent the energy of Snow Alien.

My thinks.
