### ISSUE TITLE
Issue with Shadows in terminal

### ISSUE THREAD

**Issue by BharatKalluri** [EliverLara/snow#4]
Hello!

Love your work! But the white shadows in the terminal.
![shadow problem](https://user-images.githubusercontent.com/8049414/43817238-045d2e04-9af6-11e8-93ba-7dc2052665ca.png)

Can you make these shadows less prominent or remove them.

Thanks!

**Comment by EliverLara** [comment]
Hi, you're right that looks odd, i just remove them.
